server:
  port: 8088

spring:
  thymeleaf:
    cache: false  # 캐시를 비활성화하거나 필요한대로 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharing_to_do
    username: namiga
    password: namiga
  jpa:
    hibernate:
      ddl-auto: update  # 필요한 DDL 설정으로 변경
    show-sql: true  # SQL 쿼리 출력 여부 설정
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: EOs_81IQFHly7VkzcFDt
            client-secret: EyD1SV9oXm
            redirect-uri: http://8088/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
            client-name: "Naver"
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: "response" #회원 정보를 json 형식으로 받는데 response 라는 키 값으로 네이버가 리턴해줌
  session:
    store-type: jdbc
  application:
    name: 나눠 볼 가